table.insert(GLOBAL.STRINGS, "DFV_LANG")
table.insert(GLOBAL.STRINGS, "DFV_HUNGER")
table.insert(GLOBAL.STRINGS, "DFV_HEALTH")
table.insert(GLOBAL.STRINGS, "DFV_SANITY")
table.insert(GLOBAL.STRINGS, "DFV_SPOILSOON")
table.insert(GLOBAL.STRINGS, "DFV_SPOILIN")
table.insert(GLOBAL.STRINGS, "DFV_SPOILDAY")

GLOBAL.STRINGS.DFV_LANG = "开"
GLOBAL.STRINGS.DFV_HUNGER = "饥饿值"
GLOBAL.STRINGS.DFV_HEALTH = "血量"
GLOBAL.STRINGS.DFV_SANITY = "精神"
GLOBAL.STRINGS.DFV_SPOILSOON = "保质期长"
GLOBAL.STRINGS.DFV_SPOILIN = "保质期"
GLOBAL.STRINGS.DFV_SPOILDAY = "日"